### ISSUE TITLE
How can arrange image through embeded htlm code

### ISSUE THREAD

**Issue by igoumeninja** [renard/o-blog#144] opened 2015-03-20 15:18 UTC
With following code:
```
#+begin_o_blog_row 8
#+BEGIN_VERSE
Σύρε να πεις της μάνας σου
να κάνει κι άλλη γέννα
να κάψει κι αλλουνού καρδιά
ως έκαψε και μένα.

Αμάν γιάλα όπα γιάλα
τα ματάκια σου τα μαύρα
τα ματάκια σου τα μαύρα
που είναι όλο φωτιά και λαύρα.

Μελαχρινό με τις ελιές
και με τα μαύρα μάτια
έκανες την καρδούλα μου
σαράντα δυο κομμάτια.

Βλέπεις εκείνο το βουνό
που άναψε και καίει;
δεν είν’ φωτιά, δεν είν’ καπνός,
αγάπη είναι, και κλαίει.

Ως και οι πέτρες που πατώ,
κι αυτές παραμιλούνε:
ποιος είν’ αυτός που μας πατά
τι λυπημένος που ‘ναι.
#+END_VERSE
#+o_blog_row_column 4
#+BEGIN_HTML
<div class="hero-unit" style="font-size: 80%;">
<img src="https://googledrive.com/host/0B0u4f2Om_ugSbl96OGhrSmk1VlU/kids.png" border="0"></a>

<p> </p>
<body><iframe width="250" height="205" src="http://www.youtube.com/embed/8Eo3AW6Howw" frameborder="0" allowfullscreen></iframe></body>
</center>
</div>
#+END_HTML
#+end_o_blog_row
```
I am taking the result:

![screen shot 2015-03-20 at 12 56 17 pm](https://cloud.githubusercontent.com/assets/155644/6752177/0aaa2f44-cf04-11e4-8659-1afe6fb521ed.png)

Is there any way to align the image and the embedded YouTube video to fit in a good way at the left;
Thanks in advance

**Comment by renard** [comment] 2015-04-14 14:56
The problem is that your HTML code is not valid. (ei `body` tag, closing `center` etc...)

Anyway o-blog uses bootstrap framework you can find documentation here http://getbootstrap.com/css/#helper-classes-floats on how to pull elements on left or right.

**Closed by renard** 2015-04-14 14:56 UTC
